# Generated by Django 5.1.5 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_likes_count_post_comments_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='event_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('event', 'Event'), ('article', 'Article')], default='post', max_length=10),
        ),
    ]
