# Generated by Django 5.1.5 on 2026-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_bio_user_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_visible',
            field=models.BooleanField(default=True),
        ),
    ]
