# Generated by Django 5.1.5 on 2026-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_position_y',
            field=models.FloatField(default=50),
        ),
    ]
