# Generated by Django 5.1.5 on 2026-04-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like_post', 'Liked your post'), ('like_comment', 'Liked your comment'), ('like_reply', 'Liked your reply'), ('comment', 'Commented on your post'), ('reply', 'Replied to your comment'), ('friend_request', 'Sent you a friend request'), ('friend_accept', 'Accepted your friend request')], max_length=20),
        ),
    ]
